### ISSUE TITLE
Flathup URL does not show anything

### ISSUE THREAD

**Issue by endertunc** [flathub/org.videolan.VLC.Plugin.bdj#2]
I found this plugin today and it worked like a charm. Thanks for the contribution! However, I found that flathub page (https://flathub.org/apps/details/org.videolan.VLC.Plugin.bdj) in the description does not show anything. I also tried to search for the plugin in Software Manager in Mint 19.2 and it did not show up there as well. It would be really nice to make this plugin more visible.

**Comment by MatMaul** [comment]
I am not sure it is possible for plugins. The needed metadata seems to be there.
For the software manager, recent version shows the plugins inside the app page.
Go to VLC page, scroll down a bit and you should see the 3 plugins there.

**Comment by TingPing** [comment]
Yes the website doesn't show extensions. Ideally they would show up similar to GNOME-Software:

![](https://user-images.githubusercontent.com/798838/37436042-70287b82-27bc-11e8-8aa9-bea769eda444.png)

This is a discussion to have over at flathub/linux-store-frontend

How the Mint store works is a discussion for them.

**Comment by MatMaul** [comment]
Thanks @TingPing for the insight. I was talking about Gnome Software indeed, didn't remember Mint had a different one.
